modLoader="lowcodefml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/SlimeKnights/TinkersThings/issues"
license="MIT"
[[mods]]
    modId="tinkers_things"
    version="1.0.1"
    displayName="Tinkers' Things"
    description='''
    A fully playable example Thing Pack for Tinkers' Construct. Includes example tools, weapon, and material.
    '''
[[dependencies.tinkers_things]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_things]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.6.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_things]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0.4.2,)"
    ordering="NONE"
    side="BOTH"